services:
  alterbot:
    container_name: alterbot
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: unless-stopped
    volumes:
      - config:/usr/src/bot/config
    env_file: ./.env
  database:
    container_name: alterbot_db
    build:
      context: database
      dockerfile: ./database/Dockerfile
    restart: unless-stopped
    volumes:
      - database:/var/database
volumes:
  config:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/config
      o: bind
  database:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/database/data
      o: bind